src/Entity/Demande.php
<?php

namespace App\Entity;

use App\Repository\DemandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: DemandeRepository::class)]
class Demande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_updated = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin_demande = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'demandes')]
    #[ORM\JoinColumn(name: 'id_user_id', referencedColumnName: 'id', nullable: false)]
    private ?User $id_user = null;

    #[ORM\ManyToOne(targetEntity: Matiere::class)]
    #[ORM\JoinColumn(name: "matiere_id", referencedColumnName: "id")]
    #[Assert\NotBlank]
    private ?Matiere $id_matiere = null;

    #[ORM\Column]
    private ?int $status = null;


    #[Assert\NotBlank]
    #[ORM\Column(length: 50)]
    private ?string $sousMatiere = null;


    #[ORM\ManyToOne(inversedBy: 'demandes')]
    private ?User $assistant = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateUpdated(): ?\DateTimeInterface
    {
        return $this->date_updated;
    }

    public function setDateUpdated(\DateTimeInterface $date_updated): static
    {
        $this->date_updated = $date_updated;

        return $this;
    }

    public function getDateFinDemande(): ?\DateTimeInterface
    {
        return $this->date_fin_demande;
    }

    public function setDateFinDemande(\DateTimeInterface $date_fin_demande): static
    {
        $this->date_fin_demande = $date_fin_demande;

        return $this;
    }


    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdMatiere(): ?Matiere
    {
        return $this->id_matiere;
    }

    public function setIdMatiere(?Matiere $id_matiere): static
    {
        $this->id_matiere = $id_matiere;

        return $this;
    }

    public function getStatus(): ?int
    {

        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getSousMatiere(): ?string
    {
        return $this->sousMatiere;
    }

    public function setSousMatiere(string $sousMatiere): static
    {
        $this->sousMatiere = $sousMatiere;

        return $this;
    }


    public function getAssistant(): ?User
    {
        return $this->assistant;
    }

    public function setAssistant(?User $assistant): static
    {
        $this->assistant = $assistant;

        return $this;
    }

}

src/Controller/UpdateDemandeController.php
<?php

namespace App\Controller;

use App\Entity\Demande;
use App\Form\AutreDemande;
use App\Form\DemandeFormType;
use App\Repository\DemandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/update/demande')]
class UpdateDemandeController extends AbstractController
{
    #[Route('/', name: 'app_update_demande_index', methods: ['GET'])]
    public function index(DemandeRepository $demandeRepository): Response
    {
        $statutTab=[1=>'En attente de confirmation',2=>'Répondu par un tuteur',  3=>'Salle assignée',4=>'Terminée',5=>'Expirée',6=>'Refusée',7=>'Annulation par l\'étudiant' ,8=>'Modifier',9=>'Supprimée' ];
        return $this->render('update_demande/index.html.twig', [
            'demandes' => $demandeRepository->findBy(['id_user'=>$this->getUser()]),
            'statutTab'=>$statutTab
        ]);
    }

    #[Route('/new', name: 'app_update_demande_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $statutTab=[1=>'En attente de confirmation',2=>'Répondu par un tuteur',  3=>'Salle assignée',4=>'Terminée',5=>'Expirée',6=>'Refusée',7=>'Annulation par l\'étudiant' ,8=>'Modifier',9=>'Supprimée' ];
        return $this->redirectToRoute('app_home',[
        'statutTab'=>$statutTab]);
    }

    #[Route('/{id}', name: 'app_update_demande_show', methods: ['GET'])]
    public function show(Demande $demande): Response
    {
        $statutTab=[1=>'En attente de confirmation',2=>'Répondu par un tuteur',  3=>'Salle assignée',4=>'Terminée',5=>'Expirée',6=>'Refusée',7=>'Annulation par l\'étudiant' ,8=>'Modifier',9=>'Supprimée' ];

        return $this->render('update_demande/show.html.twig', [
            'demande' => $demande,
            'statutTab'=>$statutTab
        ]);
    }

    #[Route('/{id}/edit', name: 'app_update_demande_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Demande $demande, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DemandeFormType::class, $demande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('app_update_demande_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('update_demande/edit.html.twig', [
            'demande' => $demande,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_update_demande_delete', methods: ['POST'])]
    public function delete(Request $request, Demande $demande, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$demande->getId(), $request->request->get('_token'))) {
            $entityManager->remove($demande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_update_demande_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/update_demande/_delete_form.html.twig
w<form method="post" action="{{ path('app_update_demande_delete', {'id': demande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ demande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/update_demande/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/update_demande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Demande{% endblock %}

{% block body %}
    <h1>Edit Demande</h1>

    {{ include('update_demande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_update_demande_index') }}">back to list</a>

    {{ include('update_demande/_delete_form.html.twig') }}
{% endblock %}
{% block javascripts %}

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const matiereSelectEl = document.getElementById('demande_form_id_matiere');
            if (matiereSelectEl) {
                matiereSelectEl.addEventListener('change', function (e) {
                    const formEl = matiereSelectEl.closest('form');


                    if (formEl) {
                        const formData = new FormData(formEl);

                        fetch(formEl.action, {
                            method: formEl.method,
                            body: formData
                        })
                            .then(response => response.text())
                            .then(html => {
                                const parser = new DOMParser();
                                const doc = parser.parseFromString(html, 'text/html');
                                const newSmFormFieldEl = doc.getElementById('demande_form_sous_matiere');
                                console.log(newSmFormFieldEl)
                                if (newSmFormFieldEl) {
                                    newSmFormFieldEl.addEventListener('change', function (e) {

                                        e.target.classList.remove('is-invalid');
                                    });

                                    const existingSmFormFieldEl = document.getElementById('demande_form_sous_matiere');

                                    if (existingSmFormFieldEl) {
                                        existingSmFormFieldEl.replaceWith(newSmFormFieldEl);
                                    } else {
                                        console.error("Element with ID 'demande_form_sous_matiere' not found.");
                                    }
                                } else {
                                    console.error("New element with ID 'demande_form_sous_matiere' not found in the response.");
                                }
                            })
                            .catch(function (err) {
                                console.error('Fetch error:', err);
                            });
                    } else {
                        console.error("Form element not found.");
                    }
                });
            }
        });
    </script>




{% endblock %}

templates/update_demande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demande index{% endblock %}

{% block body %}
    <h1>Mes demandes</h1>
    <div class="container mt-4">
    <table class="table">
        <thead>
            <tr>
                <th>Id User</th>
                <th>Sous Matiere</th>
                <th>Matiere</th>
                <th>Date de mise à jour</th>
                <th>Date de fin de la demande</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for demande in demandes %}
            <tr>
                <td>{{ demande.idUser }}</td>
                <td>{{ demande.sousMatiere }}</td>
                <td>{{ demande.idMatiere }}</td>

                <td>{{ demande.dateUpdated ? demande.dateUpdated|date('Y-m-d') : '' }}</td>
                <td>{{ demande.dateFinDemande ? demande.dateFinDemande|date('Y-m-d') : '' }}</td>
                <td>{{ statutTab[demande.status]}}</td>
                <td>
                    <a href="{{ path('app_update_demande_show', {'id': demande.id}) }}">Voir</a>
                    <a href="{{ path('app_update_demande_edit', {'id': demande.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_update_demande_new') }}">Create new</a>
    </div>
{% endblock %}

templates/update_demande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Demande{% endblock %}

{% block body %}
    <h1>Create new Demande</h1>

    {{ include('update_demande/_form.html.twig') }}

    <a href="{{ path('app_update_demande_index') }}">back to list</a>
{% endblock %}

templates/update_demande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demande{% endblock %}

{% block body %}
    <h1>Demande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ demande.id }}</td>
            </tr>
            <tr>
                <th>Date_updated</th>
                <td>{{ demande.dateUpdated ? demande.dateUpdated|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin_demande</th>
                <td>{{ demande.dateFinDemande ? demande.dateFinDemande|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ statutTab[demande.status] }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_update_demande_index') }}">back to list</a>

    <a href="{{ path('app_update_demande_edit', {'id': demande.id}) }}">edit</a>

    {{ include('update_demande/_delete_form.html.twig') }}
{% endblock %}